Parameters:
  SKAvailabilityZones:
    Description: >-
      Select Two Availibity Zone to use in the Region of deployment.  If more
      than two are selected only the first two will be used.
    Type: 'List<AWS::EC2::AvailabilityZone::Name>'
  SKVPCCIDR:
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.100.24.0/21
    Description: CIDR block for the VPC
    Type: String
  SKAZ1PubCIDR:
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.100.24.0/24
    Description: CIDR block for Public subnet located in Availability Zone 1
    Type: String
  SKAZ1PrivCIDR:
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.100.25.0/24
    Description: CIDR block for Private subnet located in Availability Zone 1
    Type: String
  SKAZ2PubCIDR:
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.100.26.0/24
    Description: CIDR block for Public subnet located in Availability Zone 2
    Type: String
  SKAZ2PrivCIDR:
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.100.27.0/24
    Description: CIDR block for Private subnet located in Availability Zone 2
    Type: String
  S3BucketName:
    Description: Name of S3 Bucket with Deployment and Configuration files
    Type: String
    Default: archlab-utsystem-shibboleth-settings
  SSHKeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  NodeInstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t1.micro
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
      - m1.small
      - m1.medium
      - m1.large
      - m1.xlarge
      - m2.xlarge
      - m2.2xlarge
      - m2.4xlarge
      - m3.medium
      - m3.large
      - m3.xlarge
      - m3.2xlarge
      - m4.large
      - m4.xlarge
      - m4.2xlarge
      - m4.4xlarge
      - m4.10xlarge
      - c1.medium
      - c1.xlarge
      - c3.large
      - c3.xlarge
      - c3.2xlarge
      - c3.4xlarge
      - c3.8xlarge
      - c4.large
      - c4.xlarge
      - c4.2xlarge
      - c4.4xlarge
      - c4.8xlarge
      - g2.2xlarge
      - g2.8xlarge
      - r3.large
      - r3.xlarge
      - r3.2xlarge
      - r3.4xlarge
      - r3.8xlarge
      - i2.xlarge
      - i2.2xlarge
      - i2.4xlarge
      - i2.8xlarge
      - d2.xlarge
      - d2.2xlarge
      - d2.4xlarge
      - d2.8xlarge
      - hi1.4xlarge
      - hs1.8xlarge
      - cr1.8xlarge
      - cc2.8xlarge
      - cg1.4xlarge
    ConstraintDescription: must be a valid EC2 instance type.
  SSLCertARN:
    Description: ARN to SSL Certificate for LoadBalancer
    Type: String
    AllowedPattern: >-
      ^arn:aws:acm:us-[\w-]{5}\d:\d{12}:certificate\/[a-z0-9]{8}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{12}
    ConstraintDescription: Must be format as AWS Resource Number (ARN)
    Default: >-
      arn:aws:acm:us-east-1:011106660368:certificate/dbbfc42a-634b-40ce-9373-a0f5d38462bd
  OutagePageHost:
    Description: FQDN Hostname for Outage Page
    Type: String
    AllowedPattern: '(?=^.{4,253}$)(^((?!-)[a-zA-Z0-9-]{1,63}(?<!-)\.)+[a-zA-Z]{2,63}$)'
    ConstraintDescription: Must be a FQDN Hostname
    Default: outage.aws.utshare.utsystem.edu
  HostedZone:
    Description: Hosted Route53 Zone
    Type: String
    AllowedPattern: '(?=^.{4,253}$)(^((?!-)[a-zA-Z0-9-]{1,63}(?<!-)\.)+[a-zA-Z]{2,63}$)'
    ConstraintDescription: Must be a FQDN Zone Name without the period on the end.
    Default: archlab.utshare.utsystem.edu
  SSMPassParameter:
    Description: SSM Parameter for Zip file Password
    Type: String
    Default: DiscSrv-Password
  CreateLogGroup:
    Description: Create New LogGroup or use excisting one
    Type: String
    AllowedValues:
      - true
      - false
    Default: false
  LogGroupName:
    Description: Name of CloudWatch LogGroup to store logs in.
    Type: String
    Default: 'DiscoverySrvHosts'
Mappings:
  AWSInstanceType2Arch:
    t1.micro:
      Arch: HVM64
    t2.nano:
      Arch: HVM64
    t2.micro:
      Arch: HVM64
    t2.small:
      Arch: HVM64
    t2.medium:
      Arch: HVM64
    t2.large:
      Arch: HVM64
    m1.small:
      Arch: HVM64
    m1.medium:
      Arch: HVM64
    m1.large:
      Arch: HVM64
    m1.xlarge:
      Arch: HVM64
    m2.xlarge:
      Arch: HVM64
    m2.2xlarge:
      Arch: HVM64
    m2.4xlarge:
      Arch: HVM64
    m3.medium:
      Arch: HVM64
    m3.large:
      Arch: HVM64
    m3.xlarge:
      Arch: HVM64
    m3.2xlarge:
      Arch: HVM64
    m4.large:
      Arch: HVM64
    m4.xlarge:
      Arch: HVM64
    m4.2xlarge:
      Arch: HVM64
    m4.4xlarge:
      Arch: HVM64
    m4.10xlarge:
      Arch: HVM64
    c1.medium:
      Arch: HVM64
    c1.xlarge:
      Arch: HVM64
    c3.large:
      Arch: HVM64
    c3.xlarge:
      Arch: HVM64
    c3.2xlarge:
      Arch: HVM64
    c3.4xlarge:
      Arch: HVM64
    c3.8xlarge:
      Arch: HVM64
    c4.large:
      Arch: HVM64
    c4.xlarge:
      Arch: HVM64
    c4.2xlarge:
      Arch: HVM64
    c4.4xlarge:
      Arch: HVM64
    c4.8xlarge:
      Arch: HVM64
    g2.2xlarge:
      Arch: HVMG2
    g2.8xlarge:
      Arch: HVMG2
    r3.large:
      Arch: HVM64
    r3.xlarge:
      Arch: HVM64
    r3.2xlarge:
      Arch: HVM64
    r3.4xlarge:
      Arch: HVM64
    r3.8xlarge:
      Arch: HVM64
    i2.xlarge:
      Arch: HVM64
    i2.2xlarge:
      Arch: HVM64
    i2.4xlarge:
      Arch: HVM64
    i2.8xlarge:
      Arch: HVM64
    d2.xlarge:
      Arch: HVM64
    d2.2xlarge:
      Arch: HVM64
    d2.4xlarge:
      Arch: HVM64
    d2.8xlarge:
      Arch: HVM64
    hi1.4xlarge:
      Arch: HVM64
    hs1.8xlarge:
      Arch: HVM64
    cr1.8xlarge:
      Arch: HVM64
    cc2.8xlarge:
      Arch: HVM64
  AWSInstanceType2NATArch:
    t1.micro:
      Arch: NATHVM64
    t2.nano:
      Arch: NATHVM64
    t2.micro:
      Arch: NATHVM64
    t2.small:
      Arch: NATHVM64
    t2.medium:
      Arch: NATHVM64
    t2.large:
      Arch: NATHVM64
    m1.small:
      Arch: NATHVM64
    m1.medium:
      Arch: NATHVM64
    m1.large:
      Arch: NATHVM64
    m1.xlarge:
      Arch: NATHVM64
    m2.xlarge:
      Arch: NATHVM64
    m2.2xlarge:
      Arch: NATHVM64
    m2.4xlarge:
      Arch: NATHVM64
    m3.medium:
      Arch: NATHVM64
    m3.large:
      Arch: NATHVM64
    m3.xlarge:
      Arch: NATHVM64
    m3.2xlarge:
      Arch: NATHVM64
    m4.large:
      Arch: NATHVM64
    m4.xlarge:
      Arch: NATHVM64
    m4.2xlarge:
      Arch: NATHVM64
    m4.4xlarge:
      Arch: NATHVM64
    m4.10xlarge:
      Arch: NATHVM64
    c1.medium:
      Arch: NATHVM64
    c1.xlarge:
      Arch: NATHVM64
    c3.large:
      Arch: NATHVM64
    c3.xlarge:
      Arch: NATHVM64
    c3.2xlarge:
      Arch: NATHVM64
    c3.4xlarge:
      Arch: NATHVM64
    c3.8xlarge:
      Arch: NATHVM64
    c4.large:
      Arch: NATHVM64
    c4.xlarge:
      Arch: NATHVM64
    c4.2xlarge:
      Arch: NATHVM64
    c4.4xlarge:
      Arch: NATHVM64
    c4.8xlarge:
      Arch: NATHVM64
    g2.2xlarge:
      Arch: NATHVMG2
    g2.8xlarge:
      Arch: NATHVMG2
    r3.large:
      Arch: NATHVM64
    r3.xlarge:
      Arch: NATHVM64
    r3.2xlarge:
      Arch: NATHVM64
    r3.4xlarge:
      Arch: NATHVM64
    r3.8xlarge:
      Arch: NATHVM64
    i2.xlarge:
      Arch: NATHVM64
    i2.2xlarge:
      Arch: NATHVM64
    i2.4xlarge:
      Arch: NATHVM64
    i2.8xlarge:
      Arch: NATHVM64
    d2.xlarge:
      Arch: NATHVM64
    d2.2xlarge:
      Arch: NATHVM64
    d2.4xlarge:
      Arch: NATHVM64
    d2.8xlarge:
      Arch: NATHVM64
    hi1.4xlarge:
      Arch: NATHVM64
    hs1.8xlarge:
      Arch: NATHVM64
    cr1.8xlarge:
      Arch: NATHVM64
    cc2.8xlarge:
      Arch: NATHVM64
  AWSRegionArch2AMI:
    us-east-1:
      HVM64: ami-0b898040803850657
      HVMG2: ami-0ad82a384c06c911e
    us-west-2:
      HVM64: ami-082b5a644766e0e6f
      HVMG2: ami-006fd2260be98254c
    us-west-1:
      HVM64: ami-056ee704806822732
      HVMG2: NOT_SUPPORTED
    us-east-2:
      HVM64: ami-0d8f6eb4f641ef691
      HVMG2: ami-0f378490dca16e3f4
Conditions:
  Skip: !Equals ["0", "1"]
  Deploy: !Equals ["1", "1"]
Resources:
  2AZNetwork:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub 
        - >-
          https://${BucketName}.s3.amazonaws.com/Deployment-Stacks/Multi-AZ-Network.yaml
        - BucketName: !Ref S3BucketName
      Parameters:
        AvailabilityZones: !Join 
          - ','
          - !Ref SKAvailabilityZones
        VPCCIDR: !Ref SKVPCCIDR
        AZ1PrivCIDR: !Ref SKAZ1PrivCIDR
        AZ1PubCIDR: !Ref SKAZ1PubCIDR
        AZ2PrivCIDR: !Ref SKAZ2PrivCIDR
        AZ2PubCIDR: !Ref SKAZ2PubCIDR
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-2AZNetwork'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: a741f4b4-d4d0-4dbb-aa38-96e6c1a8c14a
  SecurityELB:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub 
        - >-
          https://${BucketName}.s3.amazonaws.com/Deployment-Stacks/Security-Load-Balancer.yaml
        - BucketName: !Ref S3BucketName
      Parameters:
        CIDRAZ1: !Ref SKAZ1PubCIDR
        CIDRAZ2: !Ref SKAZ2PubCIDR
        SSLCertARN: !Ref SSLCertARN
        S3BucketName: !Ref S3BucketName
        OutagePageHost: !Ref OutagePageHost
        HostedZone: !Ref HostedZone
        SSMPassParameter: !Ref SSMPassParameter
        CreateLogGroup: !Ref CreateLogGroup
        LogGroupName: !Ref LogGroupName
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-SecurityELB'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 7ddec924-e493-401c-bda3-54affc8f08b2
    DependsOn:
      - 2AZNetwork
  utsystemds:
    Type: 'AWS::CloudFormation::Stack'
    Condition: Skip
    Properties:
      TemplateURL: !Sub 
        - >-
          https://${BucketName}.s3.amazonaws.com/Deployment-Stacks/DiscoverySrv-Cluster.yaml
        - BucketName: !Ref S3BucketName
      Parameters:
        ClusterHost: utsystemds
        KeyName: !Ref SSHKeyName
        InstanceType: !Ref NodeInstanceType
        RulePriority: 1
        HostedZone: !Ref HostedZone
        S3BucketName: !Ref S3BucketName
        SSMPassParameter: !Ref SSMPassParameter
        LogGroupName: !Ref LogGroupName
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-utsystemds'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 398a9300-f498-4f52-8874-7e8ed269a74c
    DependsOn:
      - SecurityELB
  utshareds:
    Type: 'AWS::CloudFormation::Stack'
    Condition: Deploy
    Properties:
      TemplateURL: !Sub 
        - >-
          https://${BucketName}.s3.amazonaws.com/Deployment-Stacks/DiscoverySrv-Cluster.yaml
        - BucketName: !Ref S3BucketName
      Parameters:
        ClusterHost: utshareds
        KeyName: !Ref SSHKeyName
        InstanceType: !Ref NodeInstanceType
        RulePriority: 2
        HostedZone: !Ref HostedZone
        S3BucketName: !Ref S3BucketName
        SSMPassParameter: !Ref SSMPassParameter
        LogGroupName: !Ref LogGroupName
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-utshareds'
    DependsOn:
      - SecurityELB
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 9b4060af-b19c-4bb2-908a-3d39a26de484
  benefitsds:
    Type: 'AWS::CloudFormation::Stack'
    Condition: Skip
    Properties:
      TemplateURL: !Sub 
        - >-
          https://${BucketName}.s3.amazonaws.com/Deployment-Stacks/DiscoverySrv-Cluster.yaml
        - BucketName: !Ref S3BucketName
      Parameters:
        ClusterHost: benefitsds
        KeyName: !Ref SSHKeyName
        InstanceType: !Ref NodeInstanceType
        RulePriority: 3
        HostedZone: !Ref HostedZone
        S3BucketName: !Ref S3BucketName        
        SSMPassParameter: !Ref SSMPassParameter
        LogGroupName: !Ref LogGroupName
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-benefitsds'
    DependsOn:
      - SecurityELB
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 425231d4-d54f-4597-ba4c-3ebb6bff7af      
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Availability Zone Selection
        Parameters:
          - SKAvailabilityZones
      - Label:
          default: Virtual Private Cloud
        Parameters:
          - SKVPCCIDR
      - Label:
          default: Availability Zone 1
        Parameters:
          - SKAZ1PubCIDR
          - SKAZ1PrivCIDR
      - Label:
          default: Availability Zone 2
        Parameters:
          - SKAZ2PubCIDR
          - SKAZ2PrivCIDR
      - Label:
          default: Instance Selections
        Parameters:
          - S3BucketName
          - SSHKeyName
          - NodeInstanceType
      - Label:
          default: Other Parameters
        Parameters:
          - HostedZone
          - CreateLogGroup
          - LogGroupName
          - OutagePageHost
          - SSLCertARN
          - SSMPassParameter
    ParameterLabels:
      SKAvailabilityZones:
        default: Availability Zones
      SKVPCCIDR:
        default: Virtual Private Cloud CIDR Block
      SKAZ1PubCIDR:
        default: Public Subnet CIDR Block for Availability Zone 1
      SKAZ1PrivCIDR:
        default: Private Subnet CIDR Block for Availability Zone 1
      SKAZ2PubCIDR:
        default: Public Subnet CIDR Block for Availability Zone 2
      SKAZ2PrivCIDR:
        default: Private Subnet CIDR Block for Availability Zone 2
      S3BucketName:
        default: Bucket Name for Configuration and Deployment Scripts
      SSHKeyName:
        default: EC2 KeyPair for SSH access
      NodeInstanceType:
        default: Instance Type
      HostedZone:
        default: Route53 Hosted Zone
      CreateLogGroup:
        default: Create New CloudWatch LogGroup
      LogGroupName:
        default: CloudWatch LogGroup Name
      OutagePageHost:
        default: Outage Page Hostname
      SSLCertARN:
        default: SSL Certificate ARN
      SSMPassParameter:
        default: Zip File Password SSM Parameter Name
  'AWS::CloudFormation::Designer':
    a741f4b4-d4d0-4dbb-aa38-96e6c1a8c14a:
      size:
        width: 60
        height: 60
      position:
        x: 90
        'y': 150
      z: 1
      embeds: []
    7ddec924-e493-401c-bda3-54affc8f08b2:
      size:
        width: 60
        height: 60
      position:
        x: 210
        'y': 150
      z: 1
      embeds: []
      dependson:
        - a741f4b4-d4d0-4dbb-aa38-96e6c1a8c14a
    398a9300-f498-4f52-8874-7e8ed269a74c:
      size:
        width: 60
        height: 60
      position:
        x: 330
        'y': 150
      z: 1
      embeds: []
      dependson:
        - 7ddec924-e493-401c-bda3-54affc8f08b2
    425231d4-d54f-4597-ba4c-3ebb6bff7afe:
      size:
        width: 60
        height: 60
      position:
        x: 330
        'y': 80
      z: 1
      embeds: []
      dependson:
        - 7ddec924-e493-401c-bda3-54affc8f08b2
    9b4060af-b19c-4bb2-908a-3d39a26de484:
      size:
        width: 60
        height: 60
      position:
        x: 330
        'y': 230
      z: 1
      embeds: []
      dependson:
        - 7ddec924-e493-401c-bda3-54affc8f08b2
